version: '3.7'
services:
  mysqldb:
    image: mysql:8.0.27
    ports:
      - '3306:3306'
    volumes:
      - .data:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=touristicBooking
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass

#команда для запуска приложения
#java -jar app-deadline.jar -P:jdbc.url=jdbc:mysql://localhost:3306/app -P:jdbc.user=app -P:jdbc.password=pass