version: '3.7'
services:
  mysqldb:
    image: mysql:8.0.27
    ports:
      - '3306:3306'
    volumes:
      - .data:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=touristicBooking
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass

  node-app:
    build: .
    image: node-app:1.0
    ports:
     - '9999:9999'


  postgresql:
    image: postgres:12-alpine
    ports:
             - '5432:5432'
    volumes:
             - ./data:/var/lib/postgresql
    environment:
             - POSTGRES_PASSWORD=pass
             - POSTGRES_USER=app
             - POSTGRES_DB=postgresql
#команда для запуска приложения
#java -jar artifacts/aqa-shop.jar -P:jdbc.url=jdbc:mysql://localhost:3306/touristicBooking -P:jdbc.user=app -P:jdbc.password=pass